# Generated by Django 4.2.15 on 2024-10-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_marketstag_alter_general_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="markets",
            name="tag",
        ),
        migrations.AddField(
            model_name="markets",
            name="tags",
            field=models.ManyToManyField(
                help_text="Tags assigned to a Metenox", to="markets.marketstag"
            ),
        ),
        migrations.AddField(
            model_name="marketstag",
            name="default",
            field=models.BooleanField(
                default=False,
                help_text="This tag will be applied on every new markets if true",
            ),
        ),
    ]
