# Generated by Django 4.2.15 on 2024-10-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0003_remove_markets_tag_markets_tags_marketstag_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markets",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags assigned to a Metenox",
                to="markets.marketstag",
            ),
        ),
    ]
